- name: CreateAzureVM.Add subnet
  azure.azcollection.azure_rm_subnet:
    resource_group: xv-demos
    name: aap2-xv-demos-snet
    address_prefix: "10.2.3.0/24"
    virtual_network: xv-demos-vnet

- name: CreateAzureVM.Create public IP address
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: xv-demos
    allocation_method: Static
    name: "{{ PublicIP }}"
    tags:
      Customer: "DarlingII"
  register: output_ip_address

- name: CreateAzureVM.Public IP of VM
  debug:
    msg: "The public IP is {{ output_ip_address.state.ip_address }}."

- name: CreateAzureVM.Create Network Security Group that allows SSH
  azure.azcollection.azure_rm_securitygroup:
    resource_group: xv-demos
    name: aap2-nsg
    tags:
      Customer: "DarlingII"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound

- name: CreateAzureVM.Create virtual network interface card
  azure.azcollection.azure_rm_networkinterface:
    resource_group: xv-demos
    name: "{{ vm_name }}-NIC1"
    tags:
      Customer: "DarlingII"
    virtual_network: xv-demos-vnet
    subnet: aap2-xv-demos-snet
    public_ip_name: "{{ PublicIP }}"
    security_group: aap2-nsg

- name: CreateAzureVM.Create VM
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: xv-demos
    name: "{{ vm_name }}"
    tags:
      Customer: "DarlingII"
    vm_size: Standard_DS1_v2
    admin_username: azureuser
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/azureuser/.ssh/authorized_keys
        key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLtOm1OHusk2m5TgajVO5HdGRENo2tpfrHqXJJ16hG+0hY/q1MlR9o/sHX3pM5K+WFR5dszw3mAXr494vniTAnV4190/0iv3D3IV3Y459yev5PO+OXvSEtoaidmM6BCuOS+xEPBqSlRO2JHDG7frrpS73mL7smHCQwFXzePS0Tr/y7eJG09FTUFVtLSbwNVGPcjK4C7dvbDd5bosaQEAOBnvQApMvosu1RFvlU92brrzubgvEIcgjtBrts0SvhZkBXLkzOGe3dPjVJ9qfj68ZuIAV4Y4CsUuoxk/TqsCIly0JOUw6bbymLf6u1K06oQDEQV6ZFsqy5MgiHN/9M0KFfrNX09/sq0NjQzlCTVkCG48qARniSKoSJqpQ2B8NVqmMALnx4smkziO3WMj98wiOxkEpD1Ksbj4uGLjW12+m+L6P3HpaUmfJK+GUK+4dASK3mtCcahN21csIjuAxJGbz8ov9CdosV13YiN8Z9vBKdua6NLOesFTXUHcBhCPAzbKBTOF/B1ZmGdZt0YIhA5CsRWYoLvX9iGUAXJwZRohtoJ4RHRTfvPNAsj7QAhR90GAItiNyC4cAAJiushQLCF8Zo26ueI5HCkae6WigX0cPhTlf2EWbNIQ95wqWncaNphSGdiylMVdz30Xm1i/uJlXMtDqVnDWwJF41OFzcCF91N2w== azureuser@aap2-ac"
    network_interfaces: "{{ vm_name }}-NIC1"
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.5'
      version: latest